version: "3.9"

services:
  notes-postgres:
    image: postgres:15
    container_name: notes-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

  notes-backend:
    build: ./backend
    container_name: notes-backend
    environment:
      - PORT=3001
      - DATABASE_URL=postgres://postgres:password@notes-postgres:5432/notes_db
    ports:
      - "3001:3001"
    depends_on:
      - notes-postgres
    networks:
      - app-net

  notes-frontend:
    build:
      context: ./frontend
      # IMPORTANT: build the React app to talk to the PUBLIC IP of the VM
      args:
        REACT_APP_API_URL: http://20.84.51.7:3001
    container_name: notes-frontend
    ports:
      - "80:80"
    depends_on:
      - notes-backend
    networks:
      - app-net

networks:
  app-net:

volumes:
  pgdata:
